os:
  - osx

branches:
  only:
    - master
    - dev

env:
  - NODE_VERSION="7.0.0"

install:
  - chmod a+x ./scripts/ci.sh

script:
  - ./scripts/ci.sh



notifications:
  email:
    recipients: arkenthera@gmail.com
  on_success: never
  on_failure: always